version: "3"
services: #以下にコンテナの記述
  web: #webコンテナ・・・apatchとphpを入れるもの
    build:  #公式のイメージではなく詳細を設定する
      context: ./apache-php #buildをこのディレクトリで記述する。ここにdockerファイルを記述する
    ports: #webコンテナ内の80番ポートに接続
      - 80:80
    privileged: true #privileged(特権)・・・ファイルのアクセス権に関わるもの
    links:
        - db
    volumes: #vagtrantで言うsynced_folderの事。ファイルを共有する設定
      - "./:/var/www/html" #現在のディレクトリ(コンテナ内)のhtmlと共有
      - "./apache-php/apache.conf:/etc/httpd/conf/httpd.conf" #apache.confが修正さてた時にコンテナ内に反映されるように共有化させる
    container_name: "apache-php" #コンテナの名前を設定
  db:
    image: mysql:5.7
    environment:
         - MYSQL_ROOT_PASSWORD=root
    container_name: "mysql5.7"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
        - db
    ports:
        - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    container_name: "phpmyadmin-la" ####111111