version: "3"
services: #以下にコンテナの記述
  web: #webコンテナ・・・apatchとphpを入れるもの
    build:  #公式のイメージではなく詳細を設定する
      context: ./apache-php #buildをこのディレクトリで記述する。ここにdockerファイルを記述する
    ports: #webコンテナ内の80番ポートに接続
      - 80:80
    privileged: true #privileged(特権)・・・ファイルのアクセス権に関わるもの
    links: #dbコンテナと連携させる
      - db
    volumes: #vagtrantで言うsynced_folderの事。ファイルを共有する設定
      - "./lara-d/:/var/www/html" #現在のディレクトリ(コンテナ内)のhtmlと共有
      - "./apache-php/apache.conf:/etc/httpd/conf/httpd.conf" #apache.confが修正さてた時にコンテナ内に反映されるように共有化させる
    container_name: "apache-php" #コンテナの名前を設定
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    container_name: "mysql5.7" #このDB名が.enbの9行目になる
  phpmyadmin: #dbを管理する
    image: phpmyadmin/phpmyadmin:latest
    links: #dbコンテナと連携させる
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1 #PMA・・・php my adminのこと
      - PMA_HOST=db #15行目のdbコンテナのこと
      - PMA_USER=root #.enbのDB_USERNAMEになる
      - PMA_PASSWORD=root #.enbのDB_PASSWORDになる
    container_name: "phpmyadmin-la"